# Generated by Django 4.0.4 on 2022-05-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('title', models.CharField(max_length=10)),
                ('firstname', models.CharField(max_length=50, primary_key='true', serialize=False, unique='true')),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
