# Generated by Django 4.0.4 on 2022-05-16 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='title',
        ),
    ]
