# Generated by Django 4.0.4 on 2022-05-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_crud', '0002_remove_employee_confirm_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='title',
            field=models.CharField(choices=[('mr', 'MR'), ('mrs', 'MRS')], default='mr', max_length=10),
        ),
    ]
