# Generated by Django 4.0.4 on 2022-05-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_crud', '0003_employee_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('user', 'USER'), ('admin', 'ADMIN')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(choices=[('mr', 'Mr'), ('mrs', 'Mrs')], default='mr', max_length=10),
        ),
    ]
